import {Store} from './store';

export const AmazonFr: Store = {
  backoffStatusCodes: [403, 429, 503],
  currency: '€',
  labels: {
    captcha: {
      container: 'body',
      text: ['entrez les caractères que vous voyez ci-dessous'],
    },
    inStock: {
      container: '#desktop_buybox',
      text: ['ajouter au panier'],
    },
    maxPrice: {
      container: '#priceblock_ourprice',
    },
    outOfStock: [
      {
        container: '#availability',
        text: ['Actuellement indisponible'],
      },
    ],
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.amazon.fr/dp/B07PW9VBK5',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LNW8RR4',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LQ6F4QR',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LQ4XF6Z',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LQBLGGZ',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LDS72P2',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LDT6HQ5',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08HBJB7YD',
    },
    {
      brand: 'pny',
      model: 'uprising',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08HBF5L3K',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LNPPCWJ',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR7SV3M',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR5SXPS',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08L3QZP7W',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08L3Q41SM',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR3DPGW',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08L8L9TCZ',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR3Y5GQ',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR55YB5',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR4RJ3Q',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08L3QCZKZ',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LW46GH2',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HR6FMF3',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LNY8P5L',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LNY8P5L',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08M13DXSZ',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LNWPYRS',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08KY266MG',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08KHL21CV',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HJTH61J',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08MDCF8Z8',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08KXZV626',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08KHL2J5X',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HJS2JLJ',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08L8JNTXQ',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08HT7PR9Y',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08KHFZN9P',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08HSJ1622',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LLG9KQT',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HHDP9DW',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HH5WF97',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08HRBR7K9',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LBVNKT1',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.amazon.fr/dp/B08LF1CWT2',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.amazon.fr/dp/B08HJNKT3P',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HJQ182D',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HR9D2JS',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HJRF2CN',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HJPDJTY',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HJGNJ81',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.amazon.fr/dp/B08HJLLF7G',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.amazon.fr/dp/B08166SLDF',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.amazon.fr/dp/B0815XFSGK',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.amazon.fr/dp/B08164VTWH',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.amazon.fr/dp/B0815Y8J9N',
    },
    {
      brand: 'sony',
      model: 'ps5 console',
      series: 'sonyps5c',
      url: 'https://www.amazon.fr/dp/B08H93ZRK9',
    },
    {
      brand: 'sony',
      model: 'ps5 digital',
      series: 'sonyps5de',
      url: 'https://www.amazon.fr/dp/B08H98GVK8',
    },
    {
      brand: 'microsoft',
      model: 'xbox series x',
      series: 'xboxsx',
      url: 'https://www.amazon.fr/dp/B08H93ZRLL',
    },
    {
      brand: 'microsoft',
      model: 'xbox series s',
      series: 'xboxss',
      url: 'https://www.amazon.fr/dp/B087VM5XC6',
    },
  ],
  name: 'amazon-fr',
};
